server.port=8080

# application.properties (default - safe to commit)
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#example properties
# spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
# spring.datasource.username=your_username
# spring.datasource.password=your_password
# spring.datasource.driver-class-name=org.postgresql.Driver